title: Art Gallery
description: Apresentação do TP de Algoritmos 2
theme: just-the-docs

url: https://alexeduardo-zip.github.io/ALG2_TP1_Art/

aux_links:
  Template Repository: https://alexeduardo-zip.github.io/ALG2_TP1_Art/

plugins:
  - jekyll-default-layout
